name: CI reusable
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  workflow_call:
    inputs:
      lib:
        description: "Library folder name (relative to repo root)"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: pycram/semantic_world:jazzy
    steps:
      - uses: actions/checkout@v4
        with:
          path: cognitive_robot_abstract_machine
          submodules: recursive

      - name: Install dependencies
        run: |
          cd cognitive_robot_abstract_machine
          source /opt/ros/semantic_digital_twin-venv/bin/activate
          python3 -m pip install poetry
          poetry install

      - name: Build ORM
        if: ${{inputs.lib == 'pycram' || inputs.lib == 'semantic_digital_twin'}}
        run: |
          cd cognitive_robot_abstract_machine/${{ inputs.lib }}/scripts/
          source /opt/ros/overlay_ws/install/setup.bash
          source /opt/ros/semantic_digital_twin-venv/bin/activate
          python generate_orm.py

      - name: Run tests
        run: |
          source /opt/ros/overlay_ws/install/setup.bash
          source /opt/ros/semantic_digital_twin-venv/bin/activate
          python -m pytest -sv cognitive_robot_abstract_machine/test/${{ inputs.lib }}_test